defaults: &defaults
  site_name: Title
  site_title: 'Title - '
  site_version: 1.0.0 
  admin_email: <email@address>
  contact_email: <email@address>
  
development: &non_production_settings
  site_url: http://127.0.0.1:3000  
  <<: *defaults
 
test:
  <<: *non_production_settings

production:
   <<: *defaults
